Improve the scheduling algorithm
qutip/qutip-qip pull request #105
Opened 2021-11-01 11:38 UTC by BoxiLi

- Improve the readability of the scheduling algorithm.
- Add more commutation rules, such as CNOT and X on the targets, CNOT and Z on the control.

Most of the changes in the test file are just because of black styling.

@nathanshammah @quantshah

2021-11-09 12:20 UTC, nathanshammah requested changes
Thanks @BoxiLi. 

There is a small typo in the definition of a private function, please commit the suggestions. 

Can you please add more docstrings  in the private functions? Doesn't have to be completely in Numpy style, but more context would be good, even if the function names are quite pythonic.  

Also, are these features included in the documentation (API-doc)? Shall we add something about this?

2021-11-09 12:20 UTC, nathanshammah commented on tests/test_scheduler.py
> +def _varify_scheduled_circuit(circuit, gate_cycle_indices):
```suggestion
def _verify_scheduled_circuit(circuit, gate_cycle_indices):
```

2021-11-09 12:20 UTC, nathanshammah commented on tests/test_scheduler.py
> +    assert _varify_scheduled_circuit(circuit, gate_cycle_indices)
```suggestion
    assert _verify_scheduled_circuit(circuit, gate_cycle_indices)
```

2021-11-09 12:20 UTC, nathanshammah commented on tests/test_scheduler.py
> +    _varify_scheduled_circuit(circuit, gate_cycle_indices)
```suggestion
    _verify_scheduled_circuit(circuit, gate_cycle_indices)
```

2021-11-09 12:20 UTC, nathanshammah commented on tests/test_scheduler.py
> +    _varify_scheduled_circuit(circuit, gate_cycle_indices)
```suggestion
    _verify_scheduled_circuit(circuit, gate_cycle_indices)
```

2021-11-09 12:20 UTC, nathanshammah commented on tests/test_scheduler.py
> +    _varify_scheduled_circuit(circuit, gate_cycle_indices)
```suggestion
    _verify_scheduled_circuit(circuit, gate_cycle_indices)
```

2021-11-09 12:20 UTC, nathanshammah commented on tests/test_scheduler.py
> +    _varify_scheduled_circuit(circuit, gate_cycle_indices)
```suggestion
    _verify_scheduled_circuit(circuit, gate_cycle_indices)
```

2021-11-09 21:59 UTC, BoxiLi commented
It is described in the API-doc, currently, it is not included in the user guide though.

2021-11-16 15:13 UTC, nathanshammah commented
Is this ready for review again @BoxiLi?

2021-11-16 17:12 UTC, nathanshammah approved these changes
@BoxiLi looks fine to me. 

Very small comment: can we find some more "pythonic" name than `next_gate_ind`? `next_gate_index`? If not applicable, feel free to merge.

2021-11-20 10:02 UTC, merged