Remove comments after meaningful statements in QASM reader
qutip/qutip-qip pull request #218
Opened 2023-09-27 17:40 UTC by NoriyukiK-1qbit

QASMBench has lines that have comments after instructions, and those lines cause errors. This fix remove such comments.

2023-09-27 20:39 UTC, BoxiLi commented
Thank you! Could you add a test to `test_qasm.py` and verify that it works after adding these lines?

2023-09-27 22:35 UTC, NoriyukiK-1qbit commented
Hi BoxiLi,
Thanks for your comment. I added the test, and it worked as expected. Please find added files.
NK

2023-09-30 09:59 UTC, BoxiLi requested changes
Thank you! Looks good! I left a comment with a minor change in the test file.

2023-09-30 09:59 UTC, BoxiLi commented on tests/test_qasm.py
> +        assert False
There is no need to use try except here. If an error is raised during the execution, pytest will catch it and report the error with the corresponding error message. If the error is caught manually and replaced by assert (which throw an error if False), it actually hides the true error message.

2023-10-03 16:56 UTC, NoriyukiK-1qbit commented
Hi!
try/catch is removed as requested.

2023-10-08 14:32 UTC, BoxiLi approved these changes

2023-10-08 14:33 UTC, merged

2023-10-08 14:33 UTC, BoxiLi commented
@NoriyukiK-1qbit Thank you!