Update README
qutip/qutip-qip pull request #8
Opened 2021-03-14 14:27 UTC by BoxiLi

Add a short introduction and copies support from qutip readme.
Add installation guide.

2021-03-15 14:19 UTC, nathanshammah requested changes
Small changes suggested, thanks @BoxiLi.

2021-03-15 14:19 UTC, nathanshammah commented on README.md
> +From QuTiP 5.0, the community has decided to reduce the size of the core QuTiP package for reducing the external dependency and ease of maintenance.
```suggestion
From QuTiP 5.0, the community has decided to decrease the size of the core QuTiP package by reducing the external dependencies, in order to simplify maintenance.
```

2021-03-15 14:19 UTC, nathanshammah commented on README.md
> +Hence a few modules are separated from the core QuTiP and become QuTiP family packages.
```suggestion
Hence a few modules are separated from the core QuTiP and will become QuTiP family packages.
```

2021-03-15 14:19 UTC, nathanshammah commented on README.md
> +Compared to other libraries for quantum information processing, qutip-qip put additional emphasis on the physics layer and the interaction with the QuTiP package.
```suggestion
Compared to other libraries for quantum information processing, qutip-qip puts additional emphasis on the physics layer and the interaction with the QuTiP package.
```

2021-03-15 14:19 UTC, nathanshammah commented on README.md
> +This package is supported and maintained by the same group as QuTiP.
```suggestion
This package is supported and maintained by the same developers group as QuTiP.
```

2021-03-15 14:19 UTC, nathanshammah commented on README.md
> +at RIKEN, by the University of Sherbrooke, and by Aberystwyth University,
```suggestion
at RIKEN, by the University of Sherbrooke, by Chalmers University of Technology, by Macquarie University and by Aberystwyth University,
```

2021-03-20 16:46 UTC, BoxiLi commented
All suggestions applied. Thanks @nathanshammah

2021-03-30 09:48 UTC, merged